language: php

php:
 - 7.1

before_script:
 - cp .env .env.travis
 - composer self-update
 - composer install -n
 - php artisan key:generate
 - php artisan migrate

before_install:
 - mysql -e 'CREATE DATABASE nigel;'

services:
 - mysql

script:
 - phpunit
