language: php

php:
 - 7.1

before_script:
 - composer install -n
 - php artisan key:generate
 - php artisan migrate
 - npm install
 - npm run production

before_install:
 - mysql -e 'CREATE DATABASE nigel;'

services:
 - mysql

script:
 - vendor/bin/phpunit
